# This file was generated by GoReleaser. DO NOT EDIT.
cask "pistachio" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/pista"]
    end
  end

  version "1.57.0"

  on_macos do
    on_arm do
      sha256 "750b9437a6c6e1a308943e21ff8ee69c11cab7f0f53539b570aa25275f0cb9ee"
      url "https://github.com/winebarrel/pistachio/releases/download/v#{version}/pistachio_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "c60b97b72fddc685e6527eae64df0db1be01a4fd096c71b6cc60c1acb68fd900"
      url "https://github.com/winebarrel/pistachio/releases/download/v#{version}/pistachio_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "17e9fe6d50be986fc337c7bd87990dc61cae05df0546a96b2444ed5e7f892b5a"
      url "https://github.com/winebarrel/pistachio/releases/download/v#{version}/pistachio_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "20f2c0a0a24740ec81b876918af2e58897cdd42cf6c8b2f91e0005dfd4655469"
      url "https://github.com/winebarrel/pistachio/releases/download/v#{version}/pistachio_#{version}_linux_amd64.tar.gz"
    end
  end

  name "pistachio"
  desc "pistachio is a declarative schema management tool for PostgreSQL."
  homepage "https://github.com/winebarrel/pistachio"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pista"

  # No zap stanza required
end
