# This file was generated by GoReleaser. DO NOT EDIT.
cask "pistachio" do
  name "pistachio"
  desc "pistachio is a declarative schema management tool for PostgreSQL."
  homepage "https://github.com/winebarrel/pistachio"
  version "0.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pistachio"

  on_macos do
    on_intel do
      url "https://github.com/winebarrel/pistachio/releases/download/v#{version}/pistachio_#{version}_darwin_amd64.tar.gz"
      sha256 "1d3955c113f3ae399219b995f98cab3d72da1219593b700099f773e3ae5d55ae"
    end
    on_arm do
      url "https://github.com/winebarrel/pistachio/releases/download/v#{version}/pistachio_#{version}_darwin_arm64.tar.gz"
      sha256 "1dae6d9e5a82143fbe76fffa15251c12c45a88dc77026d95e77724609a2561d7"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/winebarrel/pistachio/releases/download/v#{version}/pistachio_#{version}_linux_amd64.tar.gz"
      sha256 "9c31c23d0f4ec2c0890e79397299d0f379b57b407ad83802572578f36c5ed1ae"
    end
    on_arm do
      url "https://github.com/winebarrel/pistachio/releases/download/v#{version}/pistachio_#{version}_linux_arm64.tar.gz"
      sha256 "ea235ead427058c7eca48c996d606f00a9497ddcd398d48c239e42e53eb8ef2b"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pistachio"]
    end
  end

  # No zap stanza required
end
