# This file was generated by GoReleaser. DO NOT EDIT.
cask "pistachio" do
  name "pistachio"
  desc "pistachio is a declarative schema management tool for PostgreSQL."
  homepage "https://github.com/winebarrel/pistachio"
  version "1.20.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pista"

  on_macos do
    on_intel do
      url "https://github.com/winebarrel/pistachio/releases/download/v#{version}/pistachio_#{version}_darwin_amd64.tar.gz"
      sha256 "000a7f49a61788e2f225ecf3c38be04c49f0c7e07f358b8fed71ac45e0f0cadb"
    end
    on_arm do
      url "https://github.com/winebarrel/pistachio/releases/download/v#{version}/pistachio_#{version}_darwin_arm64.tar.gz"
      sha256 "a3e32ea3eaef90ed73ea80752ca3d33a3cadf393dcd8d0c310e86e8927d3c46c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/winebarrel/pistachio/releases/download/v#{version}/pistachio_#{version}_linux_amd64.tar.gz"
      sha256 "0dedaabed7c5d2d3ce210941cea55f0a90766f047df7564a79b96e9c92ec754d"
    end
    on_arm do
      url "https://github.com/winebarrel/pistachio/releases/download/v#{version}/pistachio_#{version}_linux_arm64.tar.gz"
      sha256 "06833a6c961ad525a9075580f347689320ff72931b8a9e2617a725f52f6340a0"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pista"]
    end
  end

  # No zap stanza required
end
